### ISSUE TITLE
Getting lots of invalid hashes.

### ISSUE THREAD

**Issue by crypthusiast** [jtgrassie/monero-powpy#1]
`Hashrate: 20 H/s
Submitting hash: 3506bb848ea9f9872ed0ef98fc06b4de997756e66e2fc503e241a55ab7bb0f00
New job with target: 37894100
Error: {u'message': u'Invalid share', u'code': -1}
......................................................................................................................................................................
Hashrate: 20 H/s
Submitting hash: d7f50d3a636ea0912eb1431f2232ee543974f9983abcf581a93c41843fac1300
Error: {u'message': u'Invalid share', u'code': -1}
......................................................
Hashrate: 20 H/s
Submitting hash: 7769385df51fd011f065114d34ee25c8f569c26ecc6cf441ae9b35cb4b282d00
Error: {u'message': u'Invalid share', u'code': -1}
...................................................`

**Comment by jtgrassie** [comment]
Firstly you don't state which miner, which pool/solo RPC etc.

Both scripts work fine with the default config.

I'm going to close this.
